image: docker:latest

services:
  - docker:dind

stages:
  - build

variables:
  CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:docker

before_script:
  - echo "CI_REGISTRY=$CI_REGISTRY"
  - echo "CI_REGISTRY_IMAGE=$CI_REGISTRY_IMAGE"
  - echo "CONTAINER_IMAGE=$CONTAINER_IMAGE"
  - echo "CI_PROJECT_URL=$CI_PROJECT_URL"

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_IMAGE
    - docker run --rm -t -v $PWD:/work -w /work $CONTAINER_IMAGE ./k_build.sh

